server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: postgres
    password: a2001
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    web-application-type: servlet
example:
  app:
    jwtExpirationMs: '86400000'
    jwtCookieName: example
    jwtSecret: exampleSecretKey
